# Generated by Django 4.1 on 2022-12-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shp', models.FileField(upload_to='uploads/')),
                ('shx', models.FileField(upload_to='uploads/')),
                ('prj', models.FileField(upload_to='uploads/')),
                ('dbf', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
